# Generated by Django 5.0.1 on 2025-12-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('finance_manager', 'Finance Manager'), ('collector', 'Collector'), ('customer_service', 'Customer Service'), ('customer', 'Customer')], max_length=50, unique=True),
        ),
    ]
