# Generated by Django 5.0.1 on 2026-01-09 14:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Deprecated - use company FK', max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('admin', 'Company Administrator'), ('finance_manager', 'Finance Manager'), ('collector', 'Collector'), ('customer_service', 'Customer Service'), ('customer', 'Customer')], max_length=50, unique=True),
        ),
        # Remove old CharField company field before adding FK
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name (e.g., C&GS Ltd)', max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number', max_length=100, null=True, unique=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, default=dict, help_text='Address: {district, sector, cell, village, street}')),
                ('service_districts', models.JSONField(blank=True, default=list, help_text='List of districts where company provides service')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Company has been verified by system admin')),
                ('license_start_date', models.DateField(blank=True, null=True)),
                ('license_end_date', models.DateField(blank=True, null=True)),
                ('max_customers', models.IntegerField(default=1000, help_text='Maximum number of customers allowed')),
                ('max_collectors', models.IntegerField(default=50, help_text='Maximum number of collectors allowed')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('primary_color', models.CharField(default='#047857', help_text='Hex color code for branding', max_length=7)),
                ('prepaid_collection_price', models.DecimalField(decimal_places=2, default=1000.0, help_text='Price per prepaid collection in RWF', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the company', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='System admin who created this company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to (null for system admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company'),
        ),
    ]
