# Generated by Django 5.0.1 on 2025-12-01 14:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text='Unique employee/collector ID', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('national_id', models.CharField(blank=True, help_text='National ID number', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collectors/')),
                ('address', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('temporary', 'Temporary')], default='full_time', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, help_text='Assigned mobile device ID', max_length=255)),
                ('nfc_reader_id', models.CharField(blank=True, help_text='Assigned NFC reader device ID', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Average rating (1-5)', max_digits=3)),
                ('total_collections', models.IntegerField(default=0, help_text='Total number of collections completed')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the collector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collectors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account for app access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collector',
                'verbose_name_plural': 'Collectors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the service area (e.g., 'Kimironko Cell')", max_length=255)),
                ('code', models.CharField(help_text='Unique code for the area', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the area')),
                ('province', models.CharField(blank=True, help_text='Province name', max_length=100)),
                ('district', models.CharField(blank=True, help_text='District name', max_length=100)),
                ('sector', models.CharField(blank=True, help_text='Sector name', max_length=100)),
                ('cell', models.CharField(blank=True, help_text='Cell name', max_length=100)),
                ('village', models.CharField(blank=True, help_text='Village name', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, help_text='GeoJSON polygon defining area boundaries', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned')], default='active', max_length=20)),
                ('estimated_households', models.IntegerField(default=0, help_text='Estimated number of households')),
                ('estimated_customers', models.IntegerField(default=0, help_text='Number of registered customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['province', 'district', 'sector', 'cell', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Route name (e.g., 'Route A - Kimironko North')", max_length=255)),
                ('code', models.CharField(help_text='Unique route code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sequence_number', models.IntegerField(default=1, help_text='Order of this route within the service area')),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Estimated route distance in kilometers', max_digits=6)),
                ('estimated_duration_minutes', models.IntegerField(default=0, help_text='Estimated time to complete route in minutes')),
                ('path_geojson', models.JSONField(blank=True, help_text='GeoJSON LineString defining route path', null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_weekly', 'Twice Weekly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', help_text='Collection frequency', max_length=20)),
                ('collection_days', models.JSONField(blank=True, default=list, help_text="List of collection days (e.g., ['Monday', 'Thursday'])")),
                ('collection_time_start', models.TimeField(blank=True, help_text='Usual start time for collections', null=True)),
                ('collection_time_end', models.TimeField(blank=True, help_text='Usual end time for collections', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes about the route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('default_collector', models.ForeignKey(blank=True, help_text='Default collector assigned to this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_routes', to='operations.collector')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='operations.servicearea')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['service_area', 'sequence_number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='collector',
            name='service_areas',
            field=models.ManyToManyField(blank=True, help_text='Service areas this collector can work in', related_name='collectors', to='operations.servicearea'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Date of scheduled collection')),
                ('scheduled_time_start', models.TimeField(blank=True, help_text='Scheduled start time', null=True)),
                ('scheduled_time_end', models.TimeField(blank=True, help_text='Scheduled end time', null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Actual collection start time', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Actual collection completion time', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('customers_scheduled', models.IntegerField(default=0, help_text='Number of customers scheduled for collection')),
                ('customers_collected', models.IntegerField(default=0, help_text='Number of successful collections')),
                ('customers_missed', models.IntegerField(default=0, help_text='Number of missed collections')),
                ('notes', models.TextField(blank=True, help_text='Notes about this scheduled collection')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason if cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(help_text='Assigned collector for this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='operations.collector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='operations.route')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-scheduled_date', 'scheduled_time_start'],
                'indexes': [models.Index(fields=['scheduled_date', 'status'], name='operations__schedul_35b558_idx'), models.Index(fields=['collector', 'scheduled_date'], name='operations__collect_affa68_idx'), models.Index(fields=['route', 'scheduled_date'], name='operations__route_i_4eaec0_idx')],
                'unique_together': {('route', 'scheduled_date')},
            },
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['code'], name='operations__code_cb1cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['status'], name='operations__status_95f961_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['province', 'district', 'sector'], name='operations__provinc_cd81e9_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['code'], name='operations__code_d27a38_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['service_area', 'status'], name='operations__service_5445b4_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['default_collector'], name='operations__default_ffb5f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('service_area', 'sequence_number')},
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['employee_id'], name='operations__employe_faa206_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['phone'], name='operations__phone_1453db_idx'),
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['status'], name='operations__status_65caf4_idx'),
        ),
    ]
