# Generated by Django 5.0.1 on 2026-01-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_company_name_alter_role_name_company_and_more'),
        ('operations', '0002_schedule_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company employing this collector', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company managing this service area', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='accounts.company'),
        ),
    ]
