# Generated by Django 5.0.1 on 2026-01-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_company_name_alter_role_name_company_and_more'),
        ('customers', '0002_isukupay_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Waste collection company serving this customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.company'),
        ),
    ]
